import { FacilityType, type FacilityDef } from './types';

export const FACILITY_DEFS: Record<FacilityType, FacilityDef> = {
  [FacilityType.PowerPlantCoal]: {
    type: FacilityType.PowerPlantCoal,
    label: 'Coal Power Plant',
    size: 4,
    cost: 3000,
    upkeep: 100,
    radius: 0,
    powerOutput: 4000,
    pollution: 180,
  },
  [FacilityType.PowerPlantSolar]: {
    type: FacilityType.PowerPlantSolar,
    label: 'Solar Farm',
    size: 4,
    cost: 5000,
    upkeep: 60,
    radius: 0,
    powerOutput: 1800,
    pollution: 0,
  },
  [FacilityType.WaterPump]: {
    type: FacilityType.WaterPump,
    label: 'Water Pump',
    size: 2,
    cost: 800,
    upkeep: 20,
    radius: 0,
    waterOutput: 2000,
  },
  [FacilityType.WaterTower]: {
    type: FacilityType.WaterTower,
    label: 'Water Tower',
    size: 1,
    cost: 400,
    upkeep: 8,
    radius: 0,
    waterOutput: 600,
  },
  [FacilityType.PoliceStation]: {
    type: FacilityType.PoliceStation,
    label: 'Police Station',
    size: 2,
    cost: 500,
    upkeep: 35,
    radius: 12,
  },
  [FacilityType.FireStation]: {
    type: FacilityType.FireStation,
    label: 'Fire Station',
    size: 2,
    cost: 500,
    upkeep: 35,
    radius: 12,
  },
  [FacilityType.Hospital]: {
    type: FacilityType.Hospital,
    label: 'Hospital',
    size: 3,
    cost: 900,
    upkeep: 50,
    radius: 14,
  },
  [FacilityType.School]: {
    type: FacilityType.School,
    label: 'School',
    size: 2,
    cost: 600,
    upkeep: 30,
    radius: 10,
  },
  [FacilityType.Park]: {
    type: FacilityType.Park,
    label: 'Park',
    size: 1,
    cost: 100,
    upkeep: 5,
    radius: 6,
  },
};

export const FACILITY_LIST = Object.values(FACILITY_DEFS);
